export const FETCH_REPOSITORIES = 'app/Home/FETCH_REPOSITORIES';
export const FETCH_REPOSITORIES_RECEIVED = 'app/Home/FETCH_REPOSITORIES_RECEIVED';
export const FETCH_REPOSITORIES_FAILED = 'app/Home/FETCH_REPOSITORIES_FAILED';
