export const FETCH_REPOSITORIES = 'root/Home/FETCH_REPOSITORIES';
export const FETCH_REPOSITORIES_RECEIVED = 'root/Home/FETCH_REPOSITORIES_RECEIVED';
export const FETCH_REPOSITORIES_FAILED = 'root/Home/FETCH_REPOSITORIES_FAILED';
